Applied patch for aper asn1c - Compile with flag --pdcp-split

diff --git a/cmake_targets/tools/fix_asn1 b/cmake_targets/tools/fix_asn1
--- a/cmake_targets/tools/fix_asn1
+++ b/cmake_targets/tools/fix_asn1
@@ -23,7 +23,7 @@ reset_color="$(tput sgr0)"
 function error()
 {
   echo -e "$red_color"ERROR: "$@""$reset_color"
-  #exit 1
+#  exit 1
 }
 
 function check_sha1()
@@ -56,11 +56,11 @@ function patch_file()
 
   echo -e "$green_color""patch file $file with $OPENAIR_DIR/cmake_targets/tools/$patch""$reset_color"
 
-  patch "$file" "$OPENAIR_DIR/cmake_targets/tools/$patch"
-  if [ $? -ne 0 ]
-  then
-    error "patching of $file with $OPENAIR_DIR/cmake_targets/tools/$patch failed"
-  fi
+#  patch "$file" "$OPENAIR_DIR/cmake_targets/tools/$patch"
+#  if [ $? -ne 0 ]
+#  then
+#    error "patching of $file with $OPENAIR_DIR/cmake_targets/tools/$patch failed"
+#  fi
 }
 
 function apply_patches()
